### PR TITLE
bringing ember-drag-drop tests into modern era

### PR DESCRIPTION
**Pull request by danielspaniel**
Howdy partner,
 
  I was enjoying drag and drop so much I decided to give your testing some lovin'.

  This pull request does a few things:

   - gets rid of dependency on application level helpers like `triggerEvent` and `andThen`
      - therefore, you can now run integration component tests without the cost of starting an application 
      - therefore, yours/and everyone elses drag/drop tests now run 2X faster than they used to
   - All tests now use async/await syntax making them much slimmer
  
  Now if you thought the loveliness ended there, you would be mistaken. 
 
  - there is a new MockEvent class that replaced the old MockEventCreator
  - using ember-native-dom-helpers everywhere
  - The drag drop helper was changed / modified 
    - use async/await 
    - uses only native dom events
    - has new afterDrag callback
    - has new dragOver option to list the positions and selectors for making dragover events

  Wait theres more:
  
  - you can now use drag/drop helper for mocking a sort action 
  - The sortable-objects (component) tests now use the new drag/drop helper 
    - you don't have to unscrew your brain to understand those tests
  - The old drag helper is still there if people who use this addon don't want to change to new style
  - Your tests now pass in chrome AND in phantomjs  ( they used to fail on chrome ) 
  - .jshint files removed, since you are using eslint  

 And lastly:

 If you end up lovin all this lovin' I will then change the README to reflect the new ways to do things.

### CODE REVIEW

**Comment by dgavey** [comment]
Nice! Thanks so much, I haven't had much time to get to modernizing this library.  I really appreciate your work.  I'll get it pulled in soon.

**Comment by danielspaniel** [comment]
No problem @dgavey  .. I have a few tweaks to drag helper .. and maybe one day we could talk on screen hero? or something to collaborate and share ideas about this and that ?

**Comment by dwickern** [comment]
Just FYI, you need to import `helpers/drag-drop` instead of `helpers/ember-drag-drop` to get the new helper

**Comment by danielspaniel** [comment]
Right, do you want to change that on the readme ? or do you want me to?

**Comment by dgavey** [comment]
Either way, I'm a bit behind on bringing in a few changes. I'll try and find time in the next week to fix things up.

**Comment by dwickern** [comment]
The new test helper is a breaking change (it won't support jquery `:nth(1)` pseudo-selectors any more) so you might want to keep them both for a while

**Comment by danielspaniel** [comment]
@dwickern, actually just checked and the docs are correctly showing that you need to import helpers/drag-drop  , and the new helper works fine with nth-child(n) selector.  
Not sure what your talking about? can you explain that again?   The new helper is 100% definitely supposed to be a new way of writing your tests ( async / await ), and no need to start application in a component test.  I would think that people would want to rewrite their tests rather than just replace the old drag-helper with new one, since you don't get the speed boost if you only do that.

**Comment by dwickern** [comment]
The readme still says to import from `ember-drag-drop` for me

https://github.com/mharris717/ember-drag-drop#test-helpers

The new helpers use `document.querySelector` instead of jquery so the specific example in the readme will not work.
```
> document.querySelector('.draggable-object-target:eq(1)')
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '.draggable-object-target:eq(1)' is not a valid selector.
```

**Comment by danielspaniel** [comment]
Ahh .. I see @dwickern, that is because the documentation update I did has not been merged yet. 
 And, yes, your right, I should change that README  selector to something that works with new helper. Good point.

**Pull request merged**
