### PR TITLE
Remove jquery/native-dom usage

### PR DESCRIPTION
**Pull request by mastastealth**
I think this clears out all the deprecated stuff, and updates tests to the newer format.

### CODE REVIEW

**Comment by dgavey** [comment]
Gonna do a maintenance release then I'll pull this one in as part of a bigger upgrade.

**Comment by jherdman** [comment]
Hey friends. I thought I'd poke gently on this to see where it's at. Is there anything I can do to help?

**Comment by dgavey** [comment]
I'm planning to get some updates done soon. Sorry about the delay.

**Comment by erichonkanen** [comment]
any movement?

**Pull request merged**
