### PR TITLE
Fix file URLs on the dummy app's sortdata page

### PR DESCRIPTION
**Pull request by lolmaus**

### CODE REVIEW

**Comment by dgavey** [comment]
Awesome thanks, good timing, I'm just working on a new release right now

**Comment by lolmaus** [comment]
Any ETA on dragging between sortable containers?

I need to build a tree where you can drag any node into/out of/next to any other node.

Long time ago I built one with jQuery UI Sortable: [frontend prototype](http://hivemindunit.github.io/hivemind-frontend-prototype/settings/domains/categories2/).

It took me quite a while to resolve various problems and figure out good UI, but since day one it had been clear that the task was doable.

It's surprising how much more difficult it is to implement it with Ember, due to lack of high-level abstractions like in jQuery UI Sortable.

Do you think `ember-drag-drop` will allow building a tree like the one linked to above? Should I wait for some days or look for another solution?

PS Will be glad to be an early adopter, tester and maybe even a contributor.

**Comment by dgavey** [comment]
I currently have a PR submitted that allows for multiple and nested sortable objects.  This sounds like something that would allow you to do that.  I have to go through the PR more closely and add some tests before I can release it.  But that might be possible in the next week.  You can certainly try the PR's branch and see if that works for you.

https://github.com/mharris717/ember-drag-drop/pull/34

**Comment by lolmaus** [comment]
I've implemented a tree prototype on top of #34.

Let's continue the discussion there: https://github.com/Bushjumper/ember-drag-drop/pull/5

**Pull request merged**
