### PR TITLE
Update ember cli and convert to DDAU

### LINKED ISSUE #59: Closure actions
Wonderful addon! ⛵ 

Unless I'm mistaken currying + closure actions could be used instead of the current method for setting secondary arguments.

Perhaps a future version could deprecate the previous usage (simplified codebase) and align with closure actions. Will also simplify passing extra arguments for misc types of actions.

What do you think?

``` hbs
<!-- before -->
{{#draggable-object-target action="setStatus" status="Ready to Publish"}}
  Ready to Publish
{{/draggable-object-target}}

<!-- after -->
{{#draggable-object-target action=(action 'setStatus' 'Ready to Publish')}}
  Ready to Publish
{{/draggable-object-target}}
```

---

Source:
https://dockyard.com/blog/2015/10/29/ember-best-practice-stop-bubbling-and-use-closure-actions

### LINKED ISSUE #120: data down, actions up
ember-drag-drop does not follow data down, actions up (DDAU) pattern yet. It was discussed and future support announced in some issues (#115, #57, #39). How is the status about that one and is there anything blocking that change?

### LINKED ISSUE #121: Upgrade ember-cli-babel 5.x -> 6.x to eliminate deprecation warning
The current release (0.4.7) triggers an annoying deprecation warning with recent versions of Ember, which would be fixed by upgrading to the latest releases of `ember-cli-babel` (6.11.x). Please consider upgrading this [here](https://github.com/mharris717/ember-drag-drop/blob/5fe6a17cc378a07af1497373db9ea24d89ccc125/package.json#L49).

```
├─┬ ember-drag-drop@0.4.7
│ └─┬ ember-cli-babel@5.2.4
│   └── ember-cli-version-checker@1.3.1 
```

The deprecation warning looks like this and is described [here](https://github.com/ember-cli/ember-cli-version-checker/issues/48):
```
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/path/to/project/node_modules/ember-getowner-polyfill/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)
```

### PR DESCRIPTION
**Pull request by stopdropandrew**
This pull upgrades to the latest Ember (fixes #121), and in the process switches to DDAU (fixes #120  and fixes #59).

### CODE REVIEW

**Comment by dgavey** [comment]
Thanks for this! Wasn't expecting this to come in.  Obviously this will be a major breaking change for existing users.  I'll need to mark it as such.  I'll need to dig in here and explore this PR in depth first before I can pull it in.

**Comment by stopdropandrew** [comment]
Let me know if you have any questions. I tried to just forklift the addon with no changes other than moving to closure actions. Happy to help with whatever it needs to get this merged.

**Comment by thomblake** [comment]
This would be really helpful - I was about to look into filing an issue to upgrade ember-cli-babel because of a deprecation warning coming from ember-cli-version-checker, but this PR fixes that too.

**Comment by chadRoberge** [comment]
Really looking forward to this as well!

**Comment by boris-petrov** [comment]
@dgavey - is there any progress on this?

**Comment by dgavey** [comment]
Unfortunately no, I've taken a new job, and I really haven't found any extra time for working on this project currently.  If someone want's to take it up to become a maintainer, I would be happy to add them.

**Comment by boris-petrov** [comment]
@stopdropandrew - perhaps you could create separate PRs (one for the first and second commits, one for the third commit and one for the DDAU stuff) which could be reviewed and merged independently (by @dgavey and the rest of us). The first two commits are the most urgent ones right now because of the deprecation warnings. The rest could follow later and with a major version bump because of the breaking changes. Does that sound reasonable?

**Comment by boris-petrov** [comment]
@dgavey - could you take another look at this PR please? I've been using it in production for a couple of months now and seems stable.

@stopdropandrew - do you mind rebasing on master so the branch can be merged? And, if @dgavey requests so, perhaps split it into a couple of new PRs?

**Comment by boris-petrov** [comment]
@mharris717, @stopdropandrew, @dgavey - Ember 3.4 [will deprecate](https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action) `sendAction` and specifying actions without the `action` helper. This PR becomes mandatory at that point. Care to take another look? We used this branch in production for a while and there were no problems.

The breaking change can be "fixed" by incrementing the major version of the library. It's there for exactly that. :)

**Comment by dgavey** [comment]
I'll try to find time this week to at least get the addon upgraded to the latest Ember on a separate branch.

**Comment by boris-petrov** [comment]
@dgavey - Ember 3.4 is out with a million deprecation warnings. Please take another look at this PR - just copy-paste its changes into master - they do work fine. :)

There is also another deprecation warning about jQuery usages - there are issues about it [here](https://github.com/mharris717/ember-drag-drop/issues/134) and [here](https://github.com/emberjs/ember.js/issues/16849).

**Comment by dgavey** [comment]
Yes I will use this branch and create a new release off of it soon, sorry about the delay on this.

**Comment by dgavey** [comment]
Ok Merged, thanks for your patience.  You should be able to use this with 0.5.0 I'm going to get it updated to the latest ember with another version bump hopefully shortly.

**Comment by jackiehluo** [comment]
Does anyone in this thread happen to know when there are two more instances of `sendAction()` in `coordinator.js` when it looks like this PR removes all the others? Is there any workaround for that? We're getting deprecation warnings in our app from it.

**Comment by jevanlingen** [comment]
@jackiehluo: If I read the code, the [sendAction lines](https://github.com/mharris717/ember-drag-drop/blob/master/app/models/coordinator.js#L16) are still there to provide support for Ember < 1.13.

@Team: Since Ember 3.4 deprecates the `sendAction`, could the lines be either removed or skipped if a new Ember version is used?

**Pull request merged**
