### PR TITLE
Multiple sortable lists

### PR DESCRIPTION
**Pull request by remkoboschker**
I've made an attempt to change as little as possible and support dragging between sortable containers. I've basically copied as little as possible form pull request #34 from @Bushjumper to meet the requirement. Tests are passing, but I'll try and add some extra tests this weekend.

### CODE REVIEW

**Comment by remkoboschker** [comment]
another issue is that you can swap the order in sortable items. You can drag an object to another sortable list, but you can not do both a the same time i.e. while you drag to another list choose a place in the order without dropping and dragging again

**Comment by dgavey** [comment]
This is great, thanks! I'll have a closer look at it this weekend as well. Hopefully I can help fix some of the issues you stated.

**Comment by remkoboschker** [comment]
Also using a drag-handle does not seem to work

**Comment by dgavey** [comment]
Finally got around to looking at this. I did a merge of the latest work locally, but it seems to have broken a lot.  None of the dragging is working anymore.  I'll continue working on it this week. Hopefully I can get it to work post merge.

**Comment by remkoboschker** [comment]
That is strange. I have this branch working in production. Did you add a sorting scope? I still want to add some tests, but have little time.

**Comment by dgavey** [comment]
Not that strange, the last PR #50 affects the same parts of the drag co-coordinator.  I probably just missed something when I merged it. I'll work on it again tonight.

**Comment by dgavey** [comment]
Closed in favour of the manually merged #56

**Pull request closed without merging**
