### PR TITLE
First pass at adding support for multiple and nested sortable-objects…

### PR DESCRIPTION
**Pull request by Bushjumper**
…. Allows dragging between separate lists of draggable objects if they have the same overrideClass

### CODE REVIEW

**Comment by dgavey** [comment]
Wow, lots of changes to go through, seems that it's only failing one test right now.  But considering how much has changed, I'm going to need to go through it more carefully.  One thing I noticed off the top was that you remove overrideClass.  That is going to be a breaking change for people and I would like to avoid that if possible.

I'm at Ember Conference this week, so not sure how much time I'll have for going through it all.

**Comment by Bushjumper** [comment]
Yeah, sorry - it's evolving a bit on our end. 

I agree that changing overrideClass isn't great, we'll revert some of that so that there is no breaking change. Don't worry too much about reviewing at this stage, as you can see we're still customizing quite a bit for our use-case - hopefully some of our work will be re-usable though. 

Enjoy EmberConf :)

**Comment by dgavey** [comment]
Yeah I like where you are going with it,  I was planning to do a bit of a refactor to get rid of the injections and work all the way on services.  I'm sure I'll be able to use a lot of this too.

**Comment by knownasilya** [comment]
How is this coming along?

**Comment by Bushjumper** [comment]
I'm afraid I haven't made time to take it further and the changes aren't quite ready for merge. The idea of nesting and multiple sortable lists on a page are doable but it's still a little buggy. We have delayed the drag-drop feature from our app but I'll look into it more when I have some extra time :)

**Pull request closed without merging**
