### PR TITLE
Ember upgrade to 3.26

### PR DESCRIPTION
**Pull request by dgavey**
This modernizes the syntax for the templates and tests.  It does not yet move to glimmer components yet as that would require some significant breaking changes. 

I do want to do that but I feel a re-write and a new addon would be a better way of doing that.  I did start that work, but I need to finish it.  In the mean time this should at least help keep this running and deprecation free for a while longer.

### CODE REVIEW

**Comment by dgavey** [comment]
@boris-petrov If you could take a quick overview look at this I'd appreciate it.  Mostly I modernized the tests and example code in the dummy app , templates and general ember upgrades. 

I could go one step further and convert the components to native classes with the `@classic` decorator. Converting them to glimmer components however as I mentioned above would introduce some significant breaking changes.  There is a lot of cruft in this library and I would like to start from scratch using modern methods.

I don't use this addon personally anymore, so I'm a bit out of touch with how best to change it or if it even needs any changes.

**Comment by boris-petrov** [comment]
@dgavey - thank you for taking the time to do this!

I did take a very quick look, generally looks OK. I see three files with unit tests removed - why was that? Lack of time to fix them or you think they're unneeded?

Converting to native classes is possible however there is no need to go there for now. That's still not deprecated so let's minimize the changes so that if something breaks, it's easier to bisect.

Converting to Glimmer components is definitely a breaking change and would either require a major bump or a new library as you said. So no need for now.

If you're willing to start a new library using all the latest and greatest features, that would be awesome. :smile: I think a lot of people use `ember-drag-drop` and would use the new one too.

**Comment by dgavey** [comment]
@boris-petrov Thanks for looking it over.  I removed the tests because they were legacy tests and code from way back in pre Ember 1 days.  The integration tests cover it already for 2 of them.  And the other was this hidden feature I don't believe anyone used.  Again legacy items.  I'll probably merge this and do a beta release so we can get some real world testing before I take the beta flag off.  That work for you?

**Comment by boris-petrov** [comment]
Absolutely! We have a bunch of integration tests concerning `ember-drag-drop` so if something fails, I'll be sure to let you know. :smile: Thanks again!

**Comment by dgavey** [comment]
@boris-petrov Version 0.9.0-beta.0 is published

**Comment by boris-petrov** [comment]
@dgavey - it works like a charm and the deprecation errors are gone. Thank you! I'll be using this in production.

**Pull request merged**
