### PR TITLE
Allows drag and drop polyfill for mobile to determine droppable areas…

### LINKED ISSUE #3: iOS/Mobile
Would also be great if this worked on mobile.

Perhaps using the [Draggabilly](http://draggabilly.desandro.com/) library?

### PR DESCRIPTION
**Pull request by veelci**
…, resolves #3

### CODE REVIEW

**Comment by jackmatt2** [comment]
Are there plans to merge this?

**Comment by dgavey** [comment]
Forgot this was open, I'll see about doing a release this week.

**Comment by jackmatt2** [comment]
I can confirm that this pull request along with [ember-drag-drop-polyfill](https://github.com/aboveproperty/ember-drag-drop-polyfill) allows me to drag-n-drop on an android phone.

**Comment by jackmatt2** [comment]
maybe add ember-drag-drop-polyfill as a dependency ...

**Comment by dgavey** [comment]
I will add the ember-drag-drop-polyfill instructions to the readme for people who require touch events.  Worried about including it as a dependency for everyone.

**Comment by Aaronfischer** [comment]
I have been unable to get this to working for "drag handles". Any tips @jackmatt2 or @veelci?

**Pull request merged**
