### PR TITLE
[strict] when trying to use the strict resolver, the service is not found because of the casing.

### PR DESCRIPTION
**Pull request by gabrielcsapo**
Error when trying to enable the strict resolver.

```
Uncaught Error: Assertion Failed: Attempting to inject an unknown injection: 'service:dragCoordinator'
```

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@dgavey would you be able to review this change?

**Comment by gabrielcsapo** [comment]
@dgavey bump

**Comment by dgavey** [comment]
This looks fine.  Not sure what you mean by "strict resolver" can you give me more details as to what was causing the error?

**Comment by gabrielcsapo** [comment]
@dgavey we are working on moving https://github.com/stefanpenner/ember-strict-resolver into ember-resolver/strict as this will help with a lot of things like service lookup consistency and app boot time.

**Comment by gabrielcsapo** [comment]
@dgavey would you be able to merge this?

**Comment by gabrielcsapo** [comment]
@dgavey would you be able to revisit this? It is the last dependency that we are depending on that doesn't have a dashed cased service lookup.

**Comment by gabrielcsapo** [comment]
@dgavey I can't get CI to trigger anymore

**Comment by gabrielcsapo** [comment]
@dgavey would you be able to see what I can do to get the CI back?

**Comment by gabrielcsapo** [comment]
@mharris717 @dgavey would you be able to see what I can do to get the CI back?

**Pull request merged**
