### PR TITLE
Moved components into /addon for possible extension. Made the `draggable` property toggleable

### PR DESCRIPTION
**Pull request by Samsinite**
Improvements: 
- Moved components into the addon for possible extension.
- Made the `draggable` property toggleable
- Added check for existence of the draggable object before setting a property on it.

### CODE REVIEW

**Comment by mharris717** [comment]
Much appreciated. Will check it out shortly. 

Thanks!

**Comment by Samsinite** [comment]
Well, thank you as well. Your ember drag and drop addon saved me lots of
time :D. The least I can do is to try and contribute changes that I
personally found useful.

**Comment by mharris717** [comment]
FYI going to check it out this weekend.

**Comment by Samsinite** [comment]
If any of this is still useful, let me know and I'll rebase and fix the merge conflicts since the PR was created. Also, are you at emberconf?

**Comment by mharris717** [comment]
I apologize for the lack of action, been swamped with paying work recently and it's turned me into a crappy maintainer. 

Yup I'm at EmberConf, just heard Lauren talk about drag and drop :)

**Comment by mharris717** [comment]
And there is still value. There hasn't been much change since you made the PR, I'm sure I can merge with minimal trouble.

**Pull request merged**
