### PR TITLE
Run tests in chrome and firefox

### PR DESCRIPTION
**Pull request by dwickern**
On my machine, this repo's tests pass in phantomjs and safari but fail in firefox and chrome. My own project's tests also fail when I use the drag helper. Let's see if we can reproduce it in CI

### CODE REVIEW

**Comment by dwickern** [comment]
Of course the tests pass here 😠

**Comment by dwickern** [comment]
I've ran the tests now on OSX and Windows and these are my results
✅ PhantomJS
✅ Safari
✅ Internet Explorer 11
❌ Chrome (latest)
❌ Firefox (latest)

These tests fail in Chrome and Firefox:
> Integration | Component | sortable objects: sortable object renders draggable objects
> Integration | Component | sortable objects: sortable object renders draggable objects using shift algorithm

The tests drag some object and expect the order to change, but the order remains the same

**Comment by dgavey** [comment]
Yeah, I've been having troubles with that lately. Not sure what's going on with it. I don't think it's actually a bug though.

**Comment by dwickern** [comment]
Hey, yeah, I still don't know why the tests fail for me

**Comment by dgavey** [comment]
I am getting a FF fail locally, but Chrome is fine for me.  I guess if CI is happy I'm happy enough for now.

**Pull request merged**
