### PR TITLE
Move all css to dummy app.css

### PR DESCRIPTION
**Pull request by drourke**
This fixes a build issue we ran into in our app when trying to use this library, resulting from the app.css file in `app/styles/app.css`.

I believe that the style rules that existed in `app/styles/app.css` where not intended to be put there, most of them already existed in the dummy app styles, I moved the few others that existed into it and removed the file.

### CODE REVIEW

**Comment by dgavey** [comment]
You're right, I'll make sure that gets released soon.  Thanks for the PR.

**Comment by drourke** [comment]
@dgavey any chance you can merge this and https://github.com/mharris717/ember-drag-drop/pull/46 whenever you have some time. Thanks!

**Comment by dgavey** [comment]
So sorry, got side tracked, I'll try and merge and release tonight.

**Comment by drourke** [comment]
Awesome, thank you!

**Pull request merged**
