### PR TITLE
update ember-cli to 2.5.1 data to 2.5.3 and ember to 2.4.6

### PR DESCRIPTION
**Pull request by remkoboschker**
I have an issue with broken tests. The `triggerEvent` helper produces events without a `preventDefault` function causing the intergration tests to crash. @mharris717 any suggestions on how to fix?

### CODE REVIEW

**Comment by dgavey** [comment]
Thanks for updating it, it's been on my todo list for a while. I'll look at the tests and hopefully find a solution.

**Comment by dgavey** [comment]
Ok, had to inject the original event functions for preventDefault and stopPropagation in the mock events we send to the components.  Also found out that the zoom: 50% was breaking that sort code in the tests.  Got it all fixed up on another branch.  I'll open another PR with you're merged code.

Thanks again for getting the project up to date for me! Lots I'd like to do to modernize the code.  Would like to do that before I start with some of the bigger road map items.

**Comment by dgavey** [comment]
Closed in favour of PR #43

**Comment by remkoboschker** [comment]
@dgavey Could you share some the the modernizations you would like to do in the issues? What are the bigger road map items? Could you share them as issues? Perhaps people (like me) can help out.

**Comment by dgavey** [comment]
Yeah, I'll make a roadmap issue with checkboxes of things I'd like to see done.

**Pull request closed without merging**
