### PR TITLE
Convert to a v2 addon and drop support for Ember < 3.16

### PR DESCRIPTION
**Pull request by mansona**
I ran ember `init -b @embroider/addon-blueprint@latest --pnpm` and moved things around a bit.

One thing I did notice wasn't working is the Ember Data integration, but that is probably more related to the changes in Ember Data recently🙈

### CODE REVIEW

**Comment by mansona** [comment]
All the tests are green on my test PR if you want to approve the CI run then you will see it here too 👍 https://github.com/mansona/ember-drag-drop/actions/runs/8690561655

**Comment by mansona** [comment]
@dgavey I can fork it into adopted-ember-addons if that works for you? If you can add me to the npm I can then make sure it's released properly 👍 (I'm `real_ate` on npm)

**Comment by dgavey** [comment]
That would be awesome, thanks Chris.  Hopefully I have the rights to add you to the NPM, been a while since I've been in there.  I'll look into that today.

**Comment by dgavey** [comment]
Ok Invite sent.

**Comment by mansona** [comment]
@dgavey I've created https://github.com/adopted-ember-addons/ember-drag-drop and added you as a maintainer 👍 I haven't forked this repo since that would confuse people when creating PRs (they would open to the wrong place) but we can update the readme to mention the fork status 👍

**Comment by dgavey** [comment]
Sure thing, I'll update the readme to point to the fork. Once it's been released with a new version from the new fork,  I'll archive this repo.

**Comment by dgavey** [comment]
Readme updated

**Comment by mansona** [comment]
work moved to https://github.com/adopted-ember-addons/ember-drag-drop

**Pull request closed without merging**
